#!/bin/bash

ESC="\033"

cat << EOF
${ESC}[0;37m┌────────────────────────────────────────────────────────────────────────┐
│${ESC}[1;34m⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀${ESC}[0;37m ${ESC}[1;37mMiloHakai${ESC}[0;37m                            │
│${ESC}[1;34m⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀${ESC}[0;37m ────────────────────────────────────│
│${ESC}[1;34m⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣬⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀${ESC}[0;37m ${ESC}[1;34mAlgorithm:${ESC}[0;37m ED25519                 │
│${ESC}[1;34m⠀⠀⠀⠀⠀⢠⣶⠟⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⠀${ESC}[0;37m ${ESC}[1;34mEncryption:${ESC}[0;37m CURVE25519             │
│${ESC}[1;34m⠀⠀⠀⠀⢠⣿⠏⣼⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀⠀${ESC}[0;37m ${ESC}[1;34mCreated:${ESC}[0;37m 2026-01-06                │
│${ESC}[1;34m⠀⠀⠀⠀⣾⣿⡆⣿⣿⡃⣿⣧⣝⢿⡻⣿⣿⣿⣿⣿⣷⠀⠀⠀${ESC}[0;37m                                    │
│${ESC}[1;34m⠀⠀⠀⢸⣿⣿⣿⢸⣿⣴⣾⣿⣿⣯⣳⣜⢿⣿⣿⣿⣿⡇⠀⠀${ESC}[0;37m ${ESC}[1;34mFingerprint:${ESC}[0;37m                      │
│${ESC}[1;34m⠀⠀⠀⡌⣿⣿⣿⡈⣿⢀⣤⣤⣭⡉⠙⢿⡏⣿⣿⣿⣿⡇⠀⠀${ESC}[0;37m 2831 27F6 ECE9 740F               │
│${ESC}[1;34m⠀⠀⢀⢸⡟⣿⣿⢷⡌⢸⣿⣿⣿⣿⣷⡜⢷⣿⣿⣿⣿⡇⠀⠀${ESC}[0;37m 144C 0CF4 2B95 F432               │
│${ESC}[1;34m⠀⠀⠸⢘⡀⢻⣿⣦⡀⣙⡛⠛⠛⠿⠿⠿⢸⣿⣿⣿⣿⠃⠀⠀${ESC}[0;37m 79B2 8F7A                         │
│${ESC}[1;34m⠀⠀⠀⢰⠀⢠⣍⠙⠻⣿⣿⣿⣷⣶⣦⠀⣾⣿⣿⣿⠃⠀⠀⠀${ESC}[0;37m                                    │
│${ESC}[1;34m⠀⠀⠀⠈⢦⣾⢹⣿⣦⢘⣋⡁⠀⠀⢙⠃⣿⣿⠟⠁⠀⠀⠀⠀${ESC}[0;37m ${ESC}[1;34mSubkeys:${ESC}[0;37m                          │
│${ESC}[1;34m⠀⠀⠀⠀⠈⢻⣾⣿⡏⠸⣿⡿⠿⠿⠟⢀⣡⣄⠀⠀⠀⠀⠀⠀${ESC}[0;37m └─ [E] 4D48 4B12 78D5 6141        │
│${ESC}[1;34m⠀⠀⠀⠀⠀⠈⣾⠟⠀⠀⠠⢤⣼⣿⣆⢻⣿⣿⣷⡀⠀⠀⠀⠀${ESC}[0;37m                                    │
│${ESC}[1;34m⠀⠀⠀⠀⠀⠘⠁⣊⣐⡀⣴⣶⡼⠟⣡⣾⣿⣿⣿⣷⡀⠀⠀⠀${ESC}[0;37m ${ESC}[1;31mWarning:${ESC}[0;37m gpg.fail                  │
│${ESC}[1;34m⠀⠀⠀⡀⠀⢀⣴⣿⣿⣿⠿⠋⠀⠘⣻⣿⡿⢻⣿⣿⣿⢆⠀⠀${ESC}[0;37m                                    │
│${ESC}[1;34m⠀⠀⣠⡅⠐⢿⣙⠾⠿⠁⣰⣶⡾⢘⣋⣩⣾⡆⣿⣿⣿⣿⡆⠀${ESC}[0;37m ${ESC}[1;34mImport:${ESC}[0;37m                           │
│${ESC}[1;34m⠀⠀⣿⡇⠀⠀⠙⠷⢷⣶⣭⣍⡁⣾⣿⣿⣿⡗⣿⣿⣿⣿⠇⠀${ESC}[0;37m curl -s URL | gpg --import        │
│${ESC}[1;34m⠀⠀⢿⡇⠀⠀⠀⠀⣿⣶⣶⡄⢿⡛⠛⠛⠛⣸⠿⢏⠉⠀⠀⠀${ESC}[0;37m                                    │
│${ESC}[1;34m⠀⠀⠀⠃⠀⠀⠀⠀⠙⠛⠛⠁⠀⠈⠉⠀⠁⠀⠀⠀⠀⠀⠀⠀${ESC}[0;37m                                    │
└────────────────────────────────────────────────────────────────────────┘${ESC}[0m
EOF

# Output the actual PGP key
cat << 'PGPKEY'
-----BEGIN PGP PUBLIC KEY BLOCK-----
mDMEaV0cUxYJKwYBBAHaRw8BAQdAtre/fcOIA8r4SskRbs7SpE9vqimOwACyRKyG
VNu0+xe0TG1pbG9oYWthaSAoTXkgb3duIEdQRyBrZXkgOjMsIGNoZWNrIG91dCBn
cGcuZmFpbCkgPG1pbG9oYWthMUBwcm90b25tYWlsLmNvbT6IrwQTFgoAVxYhBCgx
J/bs6XQPFEwM9CuV9DJ5so96BQJpXRxTGxSAAAAAAAQADm1hbnUyLDIuNSsxLjEx
LDIsMQIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRArlfQyebKPerr+
AP9DjWLosmdQdyB+gQu1NFQVUAtOgMYIbSFYH4PLEuLzGwD/dNkltIEuZuZImPOD
FST5JdzePXSMBn5mixyxFOUyXwe4OARpXRxTEgorBgEEAZdVAQUBAQdAgWyhrdPG
LEjpLC+uCX4dy4XERp8IcU+pqnAybHjfBkADAQgHiJQEGBYKADwWIQQoMSf27Ol0
DxRMDPQrlfQyebKPegUCaV0cUxsUgAAAAAAEAA5tYW51MiwyLjUrMS4xMSwyLDEC
GwwACgkQK5X0Mnmyj3pydQEAni6ItQ577qcPRCzBFhpJY5a4ppm37bH6ZGi9U0n1
J5EA/0mTOwivgfQ2rXVyogEI3bYE/bkvX17N6FAZaqV8UK4G
=jiMj
-----END PGP PUBLIC KEY BLOCK-----
PGPKEY