#!/bin/bash

cat << 'EOF'
┌────────────────────────────────────────────────────────────────────────┐
│⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀   MiloHakai                            
│⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ────────────────────────────────────
│⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣠⣬⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀  Algorithm: ED25519                
│⠀⠀⠀⠀⠀⢠⣶⠟⣿⣿⣿⣿⣿⣿⣿⣿⣷⣤⡀⠀⠀⠀⠀⠀Encryption: CURVE25519            
│⠀⠀⠀⠀⢠⣿⠏⣼⣿⣿⠿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡀⠀⠀⠀Created: 2026-01-06               
│⠀⠀⠀⠀⣾⣿⡆⣿⣿⡃⣿⣧⣝⢿⡻⣿⣿⣿⣿⣿⣷⠀⠀⠀                                    
│⠀⠀⠀⢸⣿⣿⣿⢸⣿⣴⣾⣿⣿⣯⣳⣜⢿⣿⣿⣿⣿⡇⠀⠀Fingerprint:                      
│⠀⠀⠀⡌⣿⣿⣿⡈⣿⢀⣤⣤⣭⡉⠙⢿⡏⣿⣿⣿⣿⡇⠀⠀2831 27F6 ECE9 740F              
│⠀⠀⢀⢸⡟⣿⣿⢷⡌⢸⣿⣿⣿⣿⣷⡜⢷⣿⣿⣿⣿⡇⠀⠀144C 0CF4 2B95 F432              
│⠀⠀⠸⢘⡀⢻⣿⣦⡀⣙⡛⠛⠛⠿⠿⠿⢸⣿⣿⣿⣿⠃⠀⠀79B2 8F7A                        
│⠀⠀⠀⢰⠀⢠⣍⠙⠻⣿⣿⣿⣷⣶⣦⠀⣾⣿⣿⣿⠃⠀⠀⠀                                    
│⠀⠀⠀⠈⢦⣾⢹⣿⣦⢘⣋⡁⠀⠀⢙⠃⣿⣿⠟⠁⠀⠀⠀⠀ Subkeys:                          
│⠀⠀⠀⠀⠈⢻⣾⣿⡏⠸⣿⡿⠿⠿⠟⢀⣡⣄⠀⠀⠀⠀⠀⠀ └─ [E] 4D48 4B12 78D5 6141       
│⠀⠀⠀⠀⠀⠈⣾⠟⠀⠀⠠⢤⣼⣿⣆⢻⣿⣿⣷⡀⠀⠀⠀⠀                                    
│⠀⠀⠀⠀⠀⠘⠁⣊⣐⡀⣴⣶⡼⠟⣡⣾⣿⣿⣿⣷⡀⠀⠀⠀   Warning: gpg.fail                 
│⠀⠀⠀⡀⠀⢀⣴⣿⣿⣿⠿⠋⠀⠘⣻⣿⡿⢻⣿⣿⣿⢆⠀⠀                                    
│⠀⠀⣠⡅⠐⢿⣙⠾⠿⠁⣰⣶⡾⢘⣋⣩⣾⡆⣿⣿⣿⣿⡆⠀   Import:                            
│⠀⠀⣿⡇⠀⠀⠙⠷⢷⣶⣭⣍⡁⣾⣿⣿⣿⡗⣿⣿⣿⣿⠇⠀   curl -s https://outoftune.dev/milohakai/pgp | gpg --import       
│⠀⠀⢿⡇⠀⠀⠀⠀⣿⣶⣶⡄⢿⡛⠛⠛⠛⣸⠿⢏⠉⠀⠀⠀                                    
│⠀⠀⠀⠃⠀⠀⠀⠀⠙⠛⠛⠁⠀⠈⠉⠀⠁⠀⠀⠀⠀⠀⠀                                    
└────────────────────────────────────────────────────────────────────────┘
EOF

cat << 'PGPKEY'
-----BEGIN PGP PUBLIC KEY BLOCK-----
mDMEaV0cUxYJKwYBBAHaRw8BAQdAtre/fcOIA8r4SskRbs7SpE9vqimOwACyRKyG
VNu0+xe0TG1pbG9oYWthaSAoTXkgb3duIEdQRyBrZXkgOjMsIGNoZWNrIG91dCBn
cGcuZmFpbCkgPG1pbG9oYWthMUBwcm90b25tYWlsLmNvbT6IrwQTFgoAVxYhBCgx
J/bs6XQPFEwM9CuV9DJ5so96BQJpXRxTGxSAAAAAAAQADm1hbnUyLDIuNSsxLjEx
LDIsMQIbAwULCQgHAgIiAgYVCgkICwIEFgIDAQIeBwIXgAAKCRArlfQyebKPerr+
AP9DjWLosmdQdyB+gQu1NFQVUAtOgMYIbSFYH4PLEuLzGwD/dNkltIEuZuZImPOD
FST5JdzePXSMBn5mixyxFOUyXwe4OARpXRxTEgorBgEEAZdVAQUBAQdAgWyhrdPG
LEjpLC+uCX4dy4XERp8IcU+pqnAybHjfBkADAQgHiJQEGBYKADwWIQQoMSf27Ol0
DxRMDPQrlfQyebKPegUCaV0cUxsUgAAAAAAEAA5tYW51MiwyLjUrMS4xMSwyLDEC
GwwACgkQK5X0Mnmyj3pydQEAni6ItQ577qcPRCzBFhpJY5a4ppm37bH6ZGi9U0n1
J5EA/0mTOwivgfQ2rXVyogEI3bYE/bkvX17N6FAZaqV8UK4G
=jiMj
-----END PGP PUBLIC KEY BLOCK-----
PGPKEY
